// Code generated by protoc-gen-go.
// source: ikascrew.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	ikascrew.proto

It has these top-level messages:
	SyncRequest
	SyncReply
	EffectRequest
	EffectReply
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SyncRequest struct {
}

func (m *SyncRequest) Reset()                    { *m = SyncRequest{} }
func (m *SyncRequest) String() string            { return proto.CompactTextString(m) }
func (*SyncRequest) ProtoMessage()               {}
func (*SyncRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type SyncReply struct {
	Source  string `protobuf:"bytes,1,opt,name=source" json:"source,omitempty"`
	Type    string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Project string `protobuf:"bytes,3,opt,name=project" json:"project,omitempty"`
}

func (m *SyncReply) Reset()                    { *m = SyncReply{} }
func (m *SyncReply) String() string            { return proto.CompactTextString(m) }
func (*SyncReply) ProtoMessage()               {}
func (*SyncReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SyncReply) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *SyncReply) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *SyncReply) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

type EffectRequest struct {
	Name   string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Type   string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Effect string `protobuf:"bytes,3,opt,name=effect" json:"effect,omitempty"`
}

func (m *EffectRequest) Reset()                    { *m = EffectRequest{} }
func (m *EffectRequest) String() string            { return proto.CompactTextString(m) }
func (*EffectRequest) ProtoMessage()               {}
func (*EffectRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *EffectRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EffectRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *EffectRequest) GetEffect() string {
	if m != nil {
		return m.Effect
	}
	return ""
}

type EffectReply struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *EffectReply) Reset()                    { *m = EffectReply{} }
func (m *EffectReply) String() string            { return proto.CompactTextString(m) }
func (*EffectReply) ProtoMessage()               {}
func (*EffectReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *EffectReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*SyncRequest)(nil), "pb.SyncRequest")
	proto.RegisterType((*SyncReply)(nil), "pb.SyncReply")
	proto.RegisterType((*EffectRequest)(nil), "pb.EffectRequest")
	proto.RegisterType((*EffectReply)(nil), "pb.EffectReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Ikascrew service

type IkascrewClient interface {
	Sync(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncReply, error)
	Effect(ctx context.Context, in *EffectRequest, opts ...grpc.CallOption) (*EffectReply, error)
}

type ikascrewClient struct {
	cc *grpc.ClientConn
}

func NewIkascrewClient(cc *grpc.ClientConn) IkascrewClient {
	return &ikascrewClient{cc}
}

func (c *ikascrewClient) Sync(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncReply, error) {
	out := new(SyncReply)
	err := grpc.Invoke(ctx, "/pb.Ikascrew/Sync", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ikascrewClient) Effect(ctx context.Context, in *EffectRequest, opts ...grpc.CallOption) (*EffectReply, error) {
	out := new(EffectReply)
	err := grpc.Invoke(ctx, "/pb.Ikascrew/Effect", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Ikascrew service

type IkascrewServer interface {
	Sync(context.Context, *SyncRequest) (*SyncReply, error)
	Effect(context.Context, *EffectRequest) (*EffectReply, error)
}

func RegisterIkascrewServer(s *grpc.Server, srv IkascrewServer) {
	s.RegisterService(&_Ikascrew_serviceDesc, srv)
}

func _Ikascrew_Sync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IkascrewServer).Sync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Ikascrew/Sync",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IkascrewServer).Sync(ctx, req.(*SyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ikascrew_Effect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EffectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IkascrewServer).Effect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Ikascrew/Effect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IkascrewServer).Effect(ctx, req.(*EffectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Ikascrew_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Ikascrew",
	HandlerType: (*IkascrewServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sync",
			Handler:    _Ikascrew_Sync_Handler,
		},
		{
			MethodName: "Effect",
			Handler:    _Ikascrew_Effect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ikascrew.proto",
}

func init() { proto.RegisterFile("ikascrew.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 224 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xc1, 0x4e, 0x03, 0x21,
	0x10, 0x86, 0x6d, 0x6d, 0x68, 0x3b, 0xcd, 0xda, 0x38, 0x87, 0x86, 0xf4, 0x64, 0xb8, 0xd8, 0x13,
	0x07, 0x7d, 0x06, 0x0f, 0x9e, 0x8c, 0xeb, 0x13, 0x74, 0x71, 0x9a, 0xa8, 0x75, 0x41, 0x60, 0x63,
	0x78, 0x7b, 0xc3, 0x2c, 0xc4, 0x35, 0xf1, 0x36, 0xdf, 0x0f, 0xf3, 0x31, 0x03, 0x5c, 0xbd, 0x7d,
	0x1c, 0x83, 0xf1, 0xf4, 0xad, 0x9d, 0xb7, 0xd1, 0xe2, 0xdc, 0x75, 0xaa, 0x81, 0xcd, 0x4b, 0xea,
	0x4d, 0x4b, 0x5f, 0x03, 0x85, 0xa8, 0x9e, 0x61, 0x3d, 0xa2, 0x3b, 0x27, 0xdc, 0x81, 0x08, 0x76,
	0xf0, 0x86, 0xe4, 0xec, 0x66, 0x76, 0x58, 0xb7, 0x85, 0x10, 0x61, 0x11, 0x93, 0x23, 0x39, 0xe7,
	0x94, 0x6b, 0x94, 0xb0, 0x74, 0xde, 0xbe, 0x93, 0x89, 0xf2, 0x92, 0xe3, 0x8a, 0xea, 0x09, 0x9a,
	0x87, 0xd3, 0x89, 0x4c, 0x2c, 0x6f, 0xe4, 0xf6, 0xfe, 0xf8, 0x59, 0xa5, 0x5c, 0xff, 0xab, 0xdc,
	0x81, 0x20, 0x6e, 0x2c, 0xc6, 0x42, 0xea, 0x16, 0x36, 0x55, 0x98, 0xa7, 0x94, 0xb0, 0x0c, 0x83,
	0x31, 0x14, 0x02, 0x1b, 0x57, 0x6d, 0xc5, 0xbb, 0x57, 0x58, 0x3d, 0x96, 0x8d, 0xf1, 0x00, 0x8b,
	0xbc, 0x18, 0x6e, 0xb5, 0xeb, 0xf4, 0x64, 0xe3, 0x7d, 0xf3, 0x1b, 0xb8, 0x73, 0x52, 0x17, 0xa8,
	0x41, 0x8c, 0x7a, 0xbc, 0xce, 0x47, 0x7f, 0x66, 0xdf, 0x6f, 0xa7, 0x11, 0xdf, 0xef, 0x04, 0x7f,
	0xe6, 0xfd, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x63, 0xd0, 0x1d, 0x7f, 0x5e, 0x01, 0x00, 0x00,
}
