// Code generated by protoc-gen-go.
// source: ikascrew.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	ikascrew.proto

It has these top-level messages:
	SyncRequest
	SyncReply
	EffectRequest
	EffectReply
	SwitchRequest
	SwitchReply
	VolumeMessage
	VolumeReply
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SyncRequest struct {
}

func (m *SyncRequest) Reset()                    { *m = SyncRequest{} }
func (m *SyncRequest) String() string            { return proto.CompactTextString(m) }
func (*SyncRequest) ProtoMessage()               {}
func (*SyncRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type SyncReply struct {
	Source  int64  `protobuf:"varint,1,opt,name=source" json:"source,omitempty"`
	Type    string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Project int64  `protobuf:"varint,3,opt,name=project" json:"project,omitempty"`
}

func (m *SyncReply) Reset()                    { *m = SyncReply{} }
func (m *SyncReply) String() string            { return proto.CompactTextString(m) }
func (*SyncReply) ProtoMessage()               {}
func (*SyncReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SyncReply) GetSource() int64 {
	if m != nil {
		return m.Source
	}
	return 0
}

func (m *SyncReply) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *SyncReply) GetProject() int64 {
	if m != nil {
		return m.Project
	}
	return 0
}

type EffectRequest struct {
	Id     int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Type   string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Effect string `protobuf:"bytes,3,opt,name=effect" json:"effect,omitempty"`
}

func (m *EffectRequest) Reset()                    { *m = EffectRequest{} }
func (m *EffectRequest) String() string            { return proto.CompactTextString(m) }
func (*EffectRequest) ProtoMessage()               {}
func (*EffectRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *EffectRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *EffectRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *EffectRequest) GetEffect() string {
	if m != nil {
		return m.Effect
	}
	return ""
}

type EffectReply struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *EffectReply) Reset()                    { *m = EffectReply{} }
func (m *EffectReply) String() string            { return proto.CompactTextString(m) }
func (*EffectReply) ProtoMessage()               {}
func (*EffectReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *EffectReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type SwitchRequest struct {
	Type string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
}

func (m *SwitchRequest) Reset()                    { *m = SwitchRequest{} }
func (m *SwitchRequest) String() string            { return proto.CompactTextString(m) }
func (*SwitchRequest) ProtoMessage()               {}
func (*SwitchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *SwitchRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type SwitchReply struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *SwitchReply) Reset()                    { *m = SwitchReply{} }
func (m *SwitchReply) String() string            { return proto.CompactTextString(m) }
func (*SwitchReply) ProtoMessage()               {}
func (*SwitchReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *SwitchReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type VolumeMessage struct {
	Index int64   `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	Value float64 `protobuf:"fixed64,2,opt,name=value" json:"value,omitempty"`
}

func (m *VolumeMessage) Reset()                    { *m = VolumeMessage{} }
func (m *VolumeMessage) String() string            { return proto.CompactTextString(m) }
func (*VolumeMessage) ProtoMessage()               {}
func (*VolumeMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *VolumeMessage) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *VolumeMessage) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type VolumeReply struct {
	Success   bool      `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	ValueList []float64 `protobuf:"fixed64,2,rep,packed,name=valueList" json:"valueList,omitempty"`
}

func (m *VolumeReply) Reset()                    { *m = VolumeReply{} }
func (m *VolumeReply) String() string            { return proto.CompactTextString(m) }
func (*VolumeReply) ProtoMessage()               {}
func (*VolumeReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *VolumeReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *VolumeReply) GetValueList() []float64 {
	if m != nil {
		return m.ValueList
	}
	return nil
}

func init() {
	proto.RegisterType((*SyncRequest)(nil), "pb.SyncRequest")
	proto.RegisterType((*SyncReply)(nil), "pb.SyncReply")
	proto.RegisterType((*EffectRequest)(nil), "pb.EffectRequest")
	proto.RegisterType((*EffectReply)(nil), "pb.EffectReply")
	proto.RegisterType((*SwitchRequest)(nil), "pb.SwitchRequest")
	proto.RegisterType((*SwitchReply)(nil), "pb.SwitchReply")
	proto.RegisterType((*VolumeMessage)(nil), "pb.VolumeMessage")
	proto.RegisterType((*VolumeReply)(nil), "pb.VolumeReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Ikascrew service

type IkascrewClient interface {
	Sync(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncReply, error)
	Switch(ctx context.Context, in *SwitchRequest, opts ...grpc.CallOption) (*SwitchReply, error)
	Effect(ctx context.Context, in *EffectRequest, opts ...grpc.CallOption) (*EffectReply, error)
	PutVolume(ctx context.Context, in *VolumeMessage, opts ...grpc.CallOption) (*VolumeReply, error)
}

type ikascrewClient struct {
	cc *grpc.ClientConn
}

func NewIkascrewClient(cc *grpc.ClientConn) IkascrewClient {
	return &ikascrewClient{cc}
}

func (c *ikascrewClient) Sync(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncReply, error) {
	out := new(SyncReply)
	err := grpc.Invoke(ctx, "/pb.Ikascrew/Sync", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ikascrewClient) Switch(ctx context.Context, in *SwitchRequest, opts ...grpc.CallOption) (*SwitchReply, error) {
	out := new(SwitchReply)
	err := grpc.Invoke(ctx, "/pb.Ikascrew/Switch", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ikascrewClient) Effect(ctx context.Context, in *EffectRequest, opts ...grpc.CallOption) (*EffectReply, error) {
	out := new(EffectReply)
	err := grpc.Invoke(ctx, "/pb.Ikascrew/Effect", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ikascrewClient) PutVolume(ctx context.Context, in *VolumeMessage, opts ...grpc.CallOption) (*VolumeReply, error) {
	out := new(VolumeReply)
	err := grpc.Invoke(ctx, "/pb.Ikascrew/PutVolume", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Ikascrew service

type IkascrewServer interface {
	Sync(context.Context, *SyncRequest) (*SyncReply, error)
	Switch(context.Context, *SwitchRequest) (*SwitchReply, error)
	Effect(context.Context, *EffectRequest) (*EffectReply, error)
	PutVolume(context.Context, *VolumeMessage) (*VolumeReply, error)
}

func RegisterIkascrewServer(s *grpc.Server, srv IkascrewServer) {
	s.RegisterService(&_Ikascrew_serviceDesc, srv)
}

func _Ikascrew_Sync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IkascrewServer).Sync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Ikascrew/Sync",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IkascrewServer).Sync(ctx, req.(*SyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ikascrew_Switch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SwitchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IkascrewServer).Switch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Ikascrew/Switch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IkascrewServer).Switch(ctx, req.(*SwitchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ikascrew_Effect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EffectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IkascrewServer).Effect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Ikascrew/Effect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IkascrewServer).Effect(ctx, req.(*EffectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ikascrew_PutVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VolumeMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IkascrewServer).PutVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Ikascrew/PutVolume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IkascrewServer).PutVolume(ctx, req.(*VolumeMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Ikascrew_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Ikascrew",
	HandlerType: (*IkascrewServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sync",
			Handler:    _Ikascrew_Sync_Handler,
		},
		{
			MethodName: "Switch",
			Handler:    _Ikascrew_Switch_Handler,
		},
		{
			MethodName: "Effect",
			Handler:    _Ikascrew_Effect_Handler,
		},
		{
			MethodName: "PutVolume",
			Handler:    _Ikascrew_PutVolume_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ikascrew.proto",
}

func init() { proto.RegisterFile("ikascrew.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 339 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xcf, 0x4f, 0xea, 0x40,
	0x10, 0xa6, 0x85, 0x57, 0xe8, 0x90, 0x42, 0xde, 0xe4, 0x85, 0x34, 0xe4, 0x1d, 0xc8, 0x7a, 0xb0,
	0xa7, 0x26, 0xea, 0xd1, 0x33, 0x07, 0xa3, 0x26, 0xba, 0x24, 0xde, 0x61, 0x19, 0xb4, 0x5a, 0xe9,
	0xda, 0xdd, 0x8a, 0xfd, 0x0b, 0xfd, 0xb7, 0x4c, 0x77, 0x5b, 0x29, 0x09, 0xd1, 0x5b, 0xbf, 0xe9,
	0xf7, 0xa3, 0x33, 0x5f, 0x61, 0x94, 0xbc, 0x2c, 0x95, 0xc8, 0x69, 0x17, 0xcb, 0x3c, 0xd3, 0x19,
	0xba, 0x72, 0xc5, 0x02, 0x18, 0x2e, 0xca, 0xad, 0xe0, 0xf4, 0x56, 0x90, 0xd2, 0xec, 0x1e, 0x7c,
	0x0b, 0x65, 0x5a, 0xe2, 0x04, 0x3c, 0x95, 0x15, 0xb9, 0xa0, 0xd0, 0x99, 0x39, 0x51, 0x97, 0xd7,
	0x08, 0x11, 0x7a, 0xba, 0x94, 0x14, 0xba, 0x33, 0x27, 0xf2, 0xb9, 0x79, 0xc6, 0x10, 0xfa, 0x32,
	0xcf, 0x9e, 0x49, 0xe8, 0xb0, 0x6b, 0xc8, 0x0d, 0x64, 0xd7, 0x10, 0xcc, 0x37, 0x1b, 0x12, 0xba,
	0xce, 0xc0, 0x11, 0xb8, 0xc9, 0xba, 0xb6, 0x74, 0x93, 0xf5, 0x51, 0xbb, 0x09, 0x78, 0x64, 0x44,
	0xc6, 0xcd, 0xe7, 0x35, 0x62, 0xa7, 0x30, 0x6c, 0xcc, 0xaa, 0x2f, 0x0c, 0xa1, 0xaf, 0x0a, 0x21,
	0x48, 0x29, 0xe3, 0x37, 0xe0, 0x0d, 0x64, 0x27, 0x10, 0x2c, 0x76, 0x89, 0x16, 0x4f, 0x4d, 0xea,
	0x91, 0x94, 0xca, 0xad, 0x21, 0xfd, 0xec, 0x76, 0x09, 0xc1, 0x43, 0x96, 0x16, 0xaf, 0x74, 0x4b,
	0x4a, 0x2d, 0x1f, 0x09, 0xff, 0xc1, 0x9f, 0x64, 0xbb, 0xa6, 0x8f, 0x7a, 0x0d, 0x0b, 0xaa, 0xe9,
	0xfb, 0x32, 0x2d, 0x6c, 0x88, 0xc3, 0x2d, 0x60, 0x73, 0x18, 0x5a, 0xf1, 0x2f, 0x29, 0xf8, 0x1f,
	0x7c, 0xa3, 0xb8, 0x49, 0x94, 0x0e, 0xdd, 0x59, 0x37, 0x72, 0xf8, 0x7e, 0x70, 0xfe, 0xe9, 0xc0,
	0xe0, 0xaa, 0x2e, 0x10, 0x23, 0xe8, 0x55, 0x3d, 0xe1, 0x38, 0x96, 0xab, 0xb8, 0x55, 0xe0, 0x34,
	0xd8, 0x0f, 0x64, 0x5a, 0xb2, 0x0e, 0xc6, 0xe0, 0xd9, 0x1d, 0xf1, 0xaf, 0x79, 0xd5, 0x3e, 0xca,
	0x74, 0xdc, 0x1e, 0x7d, 0xf3, 0xed, 0x85, 0x2d, 0xff, 0xa0, 0x3a, 0xcb, 0x6f, 0x15, 0xc0, 0x3a,
	0x78, 0x06, 0xfe, 0x5d, 0xa1, 0xed, 0x82, 0x56, 0x72, 0x70, 0x29, 0x2b, 0x69, 0xed, 0xcf, 0x3a,
	0x2b, 0xcf, 0xfc, 0x7e, 0x17, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x67, 0x81, 0x4f, 0xe3, 0x90,
	0x02, 0x00, 0x00,
}
